In [91]:
import pandas as pd

In [111]:
# Import ny income file
income_df = pd.read_csv('https://raw.githubusercontent.com/tawney-kirkland/Metis_Project_1/main/data/ny_income.csv',
                       usecols = ['GeoType', 'GeogName', 'GeoID', 'Borough','Pop16plE','HH2E',
                              'HHI75t99E','HI100t149E','HI150t199E', 'HHI200plE', 'MdHHIncE', 'MnHHIncE'])

In [112]:
income_df.rename(columns = {'Pop16plE': 'above_16_pop',
                            'HH2E': 'total_households',
                           'HHI75t99E': 'income_75_99k',
                           'HI100t149E': 'income_100_149k',
                            'HI150t199E': 'income_150_199k',
                            'HHI200plE': 'income_200k_over',
                           'MdHHIncE': 'income_median',
                           'MnHHIncE': 'income_mean'},
                 inplace=True
                )

In [115]:
# Calculate the percent of households in each area within the specified income ranges
income_df['percent_75_99k'] = income_df['income_75_99k'] / income_df['total_households'] 
income_df['percent_100_149k'] = income_df['income_100_149k'] / income_df['total_households'] 
income_df['percent_150_199k'] = income_df['income_150_199k'] / income_df['total_households']
income_df['percent_200_over'] = income_df['income_200k_over'] / income_df['total_households']

# Sum percent of households with more than 100k income to determine a thresh hold
income_df['percent_above_100k'] = income_df['percent_100_149k'] + income_df['percent_150_199k'] + income_df['percent_200_over']

In [116]:
income_df.sort_values('percent_above_100k', ascending=False).head(30)

,GeoType,GeogName,GeoID,Borough,above_16_pop,total_households,income_75_99k,income_100_149k,income_150_199k,income_200k_over,income_median,income_mean,percent_75_99k,percent_100_149k,percent_150_199k,percent_200_over,percent_above_100k
74,NTA2010,Upper East Side-Carnegie Hill,MN40,Manhattan,49438,28854,2872,3910,2877,11883,155786.0,302939.0,0.099536,0.135510,0.099709,0.411832,0.647051
51,NTA2010,Battery Park City-Lower Manhattan,MN25,Manhattan,39203,22074,2100,4424,2488,7303,134266.0,192766.0,0.095135,0.200417,0.112712,0.330842,0.643970
63,NTA2010,Lincoln Square,MN14,Manhattan,51778,32655,2795,4814,4083,9930,121137.0,203752.0,0.085592,0.147420,0.125034,0.304088,0.576543
71,NTA2010,SoHo-TriBeCa-Civic Center-Little Italy,MN24,Manhattan,36989,19700,1506,2739,1588,6998,121638.0,251546.0,0.076447,0.139036,0.080609,0.355228,0.574873
73,NTA2010,Turtle Bay-East Midtown,MN19,Manhattan,45690,28991,3076,4930,3174,8540,119688.0,202545.0,0.106102,0.170053,0.109482,0.294574,0.574109
59,NTA2010,Gramercy,MN21,Manhattan,26343,14167,1743,2647,1650,3758,116266.0,172590.0,0.123032,0.186843,0.116468,0.265264,0.568575
78,NTA2010,West Village,MN23,Manhattan,61658,36906,3371,5543,4566,10722,119593.0,192741.0,0.091340,0.150192,0.123720,0.290522,0.564434
7,NTA2010,Brooklyn Heights-Cobble Hill,BK09,Brooklyn,21110,11152,1205,2013,1329,2925,116189.0,178252.0,0.108052,0.180506,0.119171,0.262285,0.561962
37,NTA2010,Park Slope-Gowanus,BK37,Brooklyn,60537,31147,3721,5877,4113,7453,113781.0,160700.0,0.119466,0.188686,0.132051,0.239285,0.560022
67,NTA2010,Midtown-Midtown South,MN17,Manhattan,26120,15507,1107,2303,1529,4722,116456.0,181291.0,0.071387,0.148514,0.098601,0.304508,0.551622
61,NTA2010,Hudson Yards-Chelsea-Flat Iron-Union Square,MN13,Manhattan,69699,42124,3507,6727,4198,11601,109092.0,184732.0,0.083254,0.159695,0.099658,0.275401,0.534755
62,NTA2010,Lenox Hill-Roosevelt Island,MN31,Manhattan,71047,43924,4581,6799,4111,12005,105539.0,170988.0,0.104294,0.154790,0.093593,0.273313,0.521697
38,NTA2010,park-cemetery-etc-Brooklyn,BK99,Brooklyn,321,165,41,32,22,30,102205.0,135692.0,0.248485,0.193939,0.133333,0.181818,0.509091
75,NTA2010,Upper West Side,MN12,Manhattan,114942,65676,6234,9729,6493,16447,99320.0,176267.0,0.094921,0.148136,0.098864,0.250426,0.497427
79,NTA2010,Yorkville,MN32,Manhattan,71542,44045,5183,8039,4271,9564,99282.0,150969.0,0.117675,0.182518,0.096969,0.217142,0.496628
69,NTA2010,Murray Hill-Kips Bay,MN20,Manhattan,43655,26059,2691,4395,2917,5255,95701.0,134337.0,0.103266,0.168656,0.111938,0.201658,0.482252
72,NTA2010,Stuyvesant Town-Cooper Village,MN50,Manhattan,19278,10480,1705,2197,1073,1780,97212.0,115504.0,0.162691,0.209637,0.102385,0.169847,0.481870
17,NTA2010,DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill,BK38,Brooklyn,35416,17585,1615,2864,1841,3735,94542.0,137363.0,0.091840,0.162866,0.104691,0.212397,0.479955
12,NTA2010,Carroll Gardens-Columbia Street-Red Hook,BK33,Brooklyn,34479,18111,1758,2716,2003,3757,91757.0,138368.0,0.097068,0.149964,0.110596,0.207443,0.468003
138,NTA2010,Annadale-Huguenot-Prince's Bay-Eltingville,SI01,Staten Island,23671,10010,1312,2265,1139,1226,92853.0,111603.0,0.131069,0.226274,0.113786,0.122478,0.462537
152,NTA2010,Rossville-Woodrow,SI32,Staten Island,17061,7435,1075,1668,923,843,93405.0,110151.0,0.144586,0.224344,0.124143,0.113383,0.461870
50,NTA2010,Windsor Terrace,BK40,Brooklyn,17522,9135,1206,1986,802,1356,91219.0,118325.0,0.132020,0.217406,0.087794,0.148440,0.453640
39,NTA2010,Prospect Heights,BK64,Brooklyn,17456,9331,1016,1775,995,1451,89061.0,117343.0,0.108884,0.190226,0.106634,0.155503,0.452363
142,NTA2010,Great Kills,SI54,Staten Island,35958,15517,2341,3807,1985,1139,91161.0,101281.0,0.150867,0.245344,0.127924,0.073403,0.446671
154,NTA2010,Todt Hill-Emerson Hill-Heartland Village-Light...,SI24,Staten Island,26686,11603,1264,2408,1115,1437,83355.0,117984.0,0.108937,0.207533,0.096096,0.123847,0.427476
139,NTA2010,Arden Heights,SI48,Staten Island,21150,9095,1126,2179,959,711,84490.0,101280.0,0.123804,0.239582,0.105443,0.078175,0.423200
140,NTA2010,Charleston-Richmond Valley-Tottenville,SI11,Staten Island,19291,8117,1201,1515,820,1082,86645.0,110587.0,0.147961,0.186645,0.101023,0.133300,0.420968
55,NTA2010,Clinton,MN15,Manhattan,41934,26448,3027,4198,2402,4426,81845.0,118236.0,0.114451,0.158727,0.090820,0.167347,0.416894
128,NTA2010,Rosedale,QN05,Queens,21978,7619,1278,1617,994,506,86452.0,96902.0,0.167739,0.212233,0.130463,0.066413,0.409109
176,NTA2010,North Riverdale-Fieldston-Riverdale,BX22,The Bronx,22410,10684,1741,1983,999,1370,85783.0,114400.0,0.162954,0.185605,0.093504,0.128229,0.407338